name: Close CR Issues Automatically

on:
  pull_request:
    branches:
      - main
#  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  auto-close-cr-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Run cleanup script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: aish-basavaraj1626/Issue-closer-repo
        run: |
          python .github/scripts/close_github_cr_issues.py
