name: Close CR Issues Automatically

on:
  push:
    branches:
      - main

#on:
#  pull_request:
#    branches:
#      - main
#  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC

jobs:
  close-cr-issues:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: wso2-enterprise/choreo  # Update if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests python-dateutil

      - name: Run cleanup script
        run: python .github/scripts/close_github_cr_issues.py